name: Deploy with Docker

on:
  push:
    paths:
      - 'qualitag/**'
      - 'qualitag_python/**'
      - '.github/workflows/docker.yml'
      - 'docker-compose.yaml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
  
      - name: Copy .env in qualitag directory
        run: cp .env qualitag/.env
  
      - name: Create credentials email json file
        run: |
          mkdir -p qualitag/src/main/resources/credentials
          echo '${{ secrets.CREDENTIALS_EMAIL }}' | jq . > qualitag/src/main/resources/credentials/credentials_email_service.json

      - name: Create stored credentials file
        run: |
          mkdir -p qualitag/src/main/resources/credentials/tokens
          echo "${{ secrets.STORED_CREDENTIAL }}" | base64 -d > qualitag/src/main/resources/credentials/tokens/StoredCredential

      - name: Create certificate files for HTTPS
        run: |
          mkdir -p qualitag/src/main/resources/credentials/certs
          echo "${{ secrets.KEYSTORE_CONTENT }}" | base64 -d > qualitag/src/main/resources/credentials/certs/keystore.p12

      - name: Build Docker image
        run: docker compose build
  
      - name: Run Docker Compose
        run: docker compose up -d
        
      - name: Run tests
        run: |
          docker compose exec -T qualitag-java ./gradlew test --info
          docker compose exec -T qualitag-python pytest -s
  
      - name: Tear down Docker environment
        run: docker compose down
