name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2       // Check out the repository
    - name: Set up JDK 21             // Set up JDK 21
      uses: actions/setup-java@v1     // Use the setup-java action
      with:
        java-version: 21
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build