name: Build and Deploy QualiTag Java
on:
  push:
#    paths:
#      - "qualitag/**"

jobs:
  build:
    name: Build Java Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x qualitag/gradlew

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: qualitag

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest
        working-directory: qualitag

      - name: Upload Checkstyle report
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: qualitag/build/reports/checkstyle     # uploading whole folder

      - name: Run JaCoCo coverage test
        run: ./gradlew jacocoTestReport
        working-directory: qualitag

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: qualitag/build/jacoco/test/html       # uploading whole folder

  docker:
    name: Build and Run Docker Compose
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build Docker image
        run: docker-compose build

      - name: Run Docker Compose
        run: docker-compose up -d
      
      - name: Run tests
        run: docker-compose exec qualitag ./gradlew test

      - name: Stop Docker Compose
        run: docker-compose down