name: Java CI

on:
  push:
    paths:
      - "qualitag/**"
      - ".github/workflows/java.yml"

jobs:
  build-and-test:
    name: Build and Test Java Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x qualitag/gradlew

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Copy .env in qualitag directory
        run: cp .env qualitag/.env

      - name: Create certificate files for HTTPS
        run: |
          mkdir -p qualitag/src/main/resources/credentials/certs
          echo "${{ secrets.KEYSTORE_CONTENT }}" | base64 -d > qualitag/src/main/resources/credentials/certs/keystore.p12

      - name: Create stored credentials file
        run: |
          mkdir -p qualitag/src/main/resources/credentials/tokens
          echo "${{ secrets.STORED_CREDENTIAL }}" | base64 -d > qualitag/src/main/resources/credentials/tokens/StoredCredential

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: qualitag

      - name: Store reports in case of failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/build/reports/
            **/build/test-results/

      - name: Upload Checkstyle report
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: qualitag/build/reports/checkstyle     # uploading whole folder

      - name: Run JaCoCo coverage test
        run: ./gradlew jacocoTestReport
        working-directory: qualitag

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: qualitag/build/jacoco/test/html       # uploading whole folder
